### ISSUE TITLE
Pub/Sub

### ISSUE THREAD

**Issue by n0ne** [ffxsam/ffx-meteor-react-boilerplate#3]
Where is pub/sub???
How add subscription, if using react from npm?

**Comment by ffxsam** [comment]
Make sure you're looking at the `example` branch:

Subscribe:
https://github.com/ffxsam/ffx-meteor-react-boilerplate/blob/example/client/containers/ColorSetterContainer.jsx#L80

Publish:
https://github.com/ffxsam/ffx-meteor-react-boilerplate/blob/example/server/publications.js

**Comment by n0ne** [comment]
Yes, I found, thank you...
But you are using mixin react-meteor-data... it is meteor, but not react way...imho
I'm looking for combination Meteor+React+Redux, but without mixins and this.data...found react-komposer from Arunoda, but have to use or composeWithTracker for Meteor, or compose for Redux...
And found this [project](https://github.com/djhi/my-nutrition), but can't undertand his middleware for subscriptions....

**Comment by ffxsam** [comment]
Of course I'm using `react-meteor-data`, since this is Meteor. :) I'm trying to stick somewhat close to MDG's official recommendations, so I'm still using their mixin.

So with my boilerplate, you would basically use `getMeteorData()` for dealing with Meteor subscriptions and reacting to data changes, and Redux would handle app state, sending updates to components via their `componentWillReceiveProps()` lifecycle method.

**Comment by n0ne** [comment]
Cool! I have to make some investigations (-:
Especially, how I can customize subscription with props, sending them from Redux through connect()...

And still waiting giude from MDG for Meteor 1.3 + React and, I hope, Redux (-:
